name       : gnome-dictionary
version    : 3.24.0
release    : 3
source     :
    - https://download.gnome.org/sources/gnome-dictionary/3.24/gnome-dictionary-3.24.0.tar.xz : 41e7064a0cfab18e881a95ce9f1712ee5c9f426904b16f3bc04c35ebd1bbd9f2
license    : GPL-2.0
component  : office
summary    : Look up definitions
description: |
    Dictionary is the GNOME application to look up definitions.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk-doc)
    - itstool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
