name       : gnome-dictionary
version    : 3.20.0
release    : 1
source     :
    - https://download.gnome.org/sources/gnome-dictionary/3.20/gnome-dictionary-3.20.0.tar.xz : efb36377d46eff9291d3b8fec37baab2355f9dc8bc7edb791b6a625574716121
license    : GPL-2.0
component  : office 
summary    : Look up definitions
description: |
    Dictionary is the GNOME application to look up definitions. 
builddeps  :
        - pkgconfig(gtk+-3.0)
        - pkgconfig(gtk-doc)
        - itstool 
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
