name       : gnome-dictionary
version    : 3.26.1
release    : 5
source     :
    - https://download.gnome.org/sources/gnome-dictionary/3.26/gnome-dictionary-3.26.1.tar.xz : 16b8bc248dcf68987826d5e39234b1bb7fd24a2607fcdbf4258fde88f012f300
license    : GPL-2.0-or-later
component  : office
summary    : Look up definitions
description: |
    Dictionary is the GNOME application to look up definitions.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
setup      : |
    %meson_configure
build      : |
    %meson_build
install    : |
    %meson_install
